import { deflateSync } from 'node:zlib';

/**
 * Generates real PNG sprite sheets for tests.
 *
 * Written rather than committed as binary fixtures so the grid, frame count and colours are
 * declared by each test, and so the upload path is exercised against genuine image bytes rather
 * than a stub. When real sprite art arrives it drops straight into the same code path.
 */

const SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer: Buffer): number {
  let c = -1;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff]! ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type: string, data: Buffer): Buffer {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);

  const typeAndData = Buffer.concat([Buffer.from(type, 'ascii'), data]);

  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typeAndData), 0);

  return Buffer.concat([length, typeAndData, crc]);
}

export interface SpriteSheetOptions {
  columns: number;
  rows: number;
  /** Pixel size of each frame; sheets are square-celled. */
  frameSize?: number;
}

/**
 * A sprite sheet where every frame is a distinct solid colour.
 *
 * Distinct colours mean a test can assert which frame is showing by sampling a pixel, and a
 * human looking at the file can see immediately whether the grid is right.
 */
export function makeSpriteSheetPng(options: SpriteSheetOptions): Buffer {
  const frameSize = options.frameSize ?? 16;
  const width = options.columns * frameSize;
  const height = options.rows * frameSize;

  // Raw RGB scanlines, each prefixed with a zero filter byte.
  const rowBytes = width * 3;
  const raw = Buffer.alloc((rowBytes + 1) * height);

  for (let y = 0; y < height; y++) {
    const rowStart = y * (rowBytes + 1);
    raw[rowStart] = 0; // filter: none

    for (let x = 0; x < width; x++) {
      const column = Math.floor(x / frameSize);
      const row = Math.floor(y / frameSize);
      const frameIndex = row * options.columns + column;

      const offset = rowStart + 1 + x * 3;
      // Spread hues across frames so neighbouring cells never look alike.
      raw[offset] = (frameIndex * 47) % 256;
      raw[offset + 1] = (frameIndex * 91) % 256;
      raw[offset + 2] = (frameIndex * 151) % 256;
    }
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour RGB
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  return Buffer.concat([
    SIGNATURE,
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** A single-frame PNG, for testing still portraits. */
export function makePortraitPng(size = 64): Buffer {
  return makeSpriteSheetPng({ columns: 1, rows: 1, frameSize: size });
}

/** Wraps generated bytes as a File, matching what a real upload delivers. */
export function asFile(bytes: Buffer, name: string, type = 'image/png'): File {
  return new File([new Uint8Array(bytes)], name, { type });
}

/** A tiny valid GIF, for testing that animated formats are stored without re-encoding. */
export function makeGif(): Buffer {
  // Smallest valid GIF89a: 1x1, one colour table entry.
  return Buffer.from(
    'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    'base64',
  );
}
